cors:
  originPatterns: http://localhost:4200,http://localhost:8080

security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000

server:
  servlet:
    context-path: /api

spring:
  #h2:
    #console:
      #enabled: true
  datasource:
    #url: jdbc:h2:mem:h2db
    #generate-unique-name: false
    #driver-class-name: org.h2.Driver
    #username: sa
    #password:
    #postgres configuration ---------
    url: jdbc:postgresql://localhost:5432/postgresdb
    generate-unique-name: false
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    #database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
spring-doc:

  swagger-ui:
    use-root-path: true

